version: 2

build:
  os: ubuntu-lts-latest
  tools:
    # just so RTD stops complaining
    python: "latest"
  apt_packages:
    - clang
  jobs:
    post_checkout:
      - sh ci/skip_rtd.sh
      - git fetch --unshallow || true
    create_environment:
      - asdf plugin add pixi
      - asdf install pixi latest
      - asdf global pixi latest
    pre_install:
      - git update-index --assume-unchanged healpix-geo-python/docs/conf.py
    install:
      - pixi install -e jupyterlite
      - pixi install -e templates
      - pixi install -e docs
    build:
      html:
        - pixi run build-emscripten
        - pixi run create-environment
        - pixi run build-docs-rtd

sphinx:
  fail_on_warning: true
  configuration: healpix-geo-python/docs/conf.py

formats: []
