[build-system]
requires = ["maturin>=1.12,<2.0"]
build-backend = "maturin"

[project]
name = "healpix-geo"
license = "Apache-2.0"
requires-python = ">=3.10"
readme = "../README.md"
classifiers = [
  "Programming Language :: Rust",
  "Programming Language :: Python :: Implementation :: CPython",
]
dependencies = ["numpy>=2.0", "marray"]
dynamic = ["version"]

[project.optional-dependencies]
geometries = ["shapely>=2"]
ragged = ["ragged", "awkward"]

[tool.maturin]
module-name = "healpix_geo._healpix_geo_python"
python-source = "python"
editable-profile = "dev"
binding = "pyo3"

[tool.coverage.run]
source = ["healpix_geo"]
branch = true

[tool.coverage.report]
show_missing = true
exclude_lines = ["pragma: no cover", "if TYPE_CHECKING"]
