name: wasm

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}.${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-bundle:
    if: github.repository == 'GRID4EARTH/healpix-geo'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Create rust cache
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # 2.9.1

      - name: setup rust
        run: |
          # TODO: pin
          cargo install wasm-pack

      - name: build node bundle
        run: |
          mkdir -p build/nodejs
          wasm-pack build js --release --target nodejs --out-name healpix_geo --out-dir build/nodejs

          ls -l build/nodejs

      - name: Upload node bundle
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: bundle-nodejs
          path: build/nodejs/*
          if-no-files-found: "error"

      - name: build esm bundle
        run: |
          mkdir -p build/esm
          wasm-pack build js --release --target web --out-name healpix_geo --out-dir build/esm

          ls -l build/esm

      - name: Upload esm bundle
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: bundle-esm
          path: build/esm/*
          if-no-files-found: "error"

      - name: build bundler bundle
        run: |
          mkdir -p build/bundler
          wasm-pack build js --release --target bundler --out-name healpix_geo --out-dir build/bundler

          ls -l build/bundler

      - name: Upload bundler bundle
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: bundle-bundler
          path: build/bundler/*
          if-no-files-found: "error"
