name: wasm

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}.${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-bundle:
    if: github.repository == 'GRID4EARTH/healpix-geo'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: js

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Create rust cache
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # 2.9.1

      - name: setup rust
        run: |
          # TODO: pin
          cargo install wasm-pack

      # - name: build node bundle
      #   run: |
      #     mkdir -p build/nodejs
      #     wasm-pack build --release --target nodejs --out-name index --out-dir build/nodejs

      # - name: build esm bundle
      #   run: |
      #     mkdir -p build/esm
      #     wasm-pack build --release --target web --out-name index --out-dir build/esm

      - name: build bundler bundle
        run: |
          mkdir -p build/bundler
          wasm-pack build --release --target bundler --out-name index --out-dir build/bundler

      - name: modify package contents
        run: |
          mkdir pkg
          cp build/bundler/index* pkg/
          jq '.files = ["*"] | .module = ["index.js"] | .types = ["index.d.ts"] | .name = "healpix-geo"' build/bundler/package.json > pkg/package.json

      # - name: assemble package
      #   run: |
      #     mkdir -p pkg/{node,esm,bundler}

      #     cp build/bundler/index* pkg/bundler
      #     cp build/esm/index* pkg/esm
      #     cp build/nodejs/index* pkg/node

      #     cp build/bundler/package.json pkg/

      #     # minimal package.json for esm
      #     echo '{"type": "module"}' > pkg/esm/package.json

      #     jq '.files = ["*"] | .module = "bundler/index.js" | .types = "bundler/index.d.ts" | .name = "healpix-geo"' pkg/package.json > package.json.tmp
      #     mv package.json.tmp pkg/package.json

      - name: Upload package
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: bundle
          path: js/pkg/*
          if-no-files-found: "error"
